name: Auto Update Markdown Menus

on:
  workflow_dispatch:
  push:
    paths:
      - 'other/menu.md'
      - '.github/workflows/menu.yml'
      - 'other/menu.sh'

jobs:
  update-menus:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Make script executable
        run: chmod +x ./other/menu.sh

      - name: Update Menus
        run: ./other/menu.sh

      - name: Commit and Push changes
        run: |
          git add .
          git diff --staged --quiet || (git commit -m "chore: update markdown menus [automated]" && git push)
